
name: Weekly dependabot checks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

permissions:
  contents: read

jobs:
  evergreen:
    name: evergreen
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Run evergreen action
        uses: github/evergreen@v1.11.2
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ORGANIZATION: mziyut
